baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Photography"
theme = "ananke-gohugo-theme"

[[menu.main]]
name               	= "Portfolio"
weight             	= 1
identifier         	= "portfolio"
url                	= "/portfolio/"

[[menu.main]]
name               	= "Om"
weight             	= 2
identifier         	= "om"
url                	= "/om/"

[[menu.main]]
name               	= "Kontakt"
weight             	= 3
identifier         	= "kontakt"
url                	= "/kontakt/"

